export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_COMPLETED_TODOS = 'REMOVE_COMPLETED_TODOS';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const CHECKED_ALL_TODOS = 'CHECKED_ALL_TODOS';
